#!/usr/bin/env python3
"""Copy project photos from the Singbuild archive into web galleries.

Usage:
    python tools/build_galleries.py [slug ...]

For each project it takes the photos from the archive's "Completion Photos" /
"Photos" folder and copies them byte-for-byte (no resizing, no re-encoding,
original quality preserved) into images/projects/<slug>/ as 01.jpg, 02.png, ...
(keeping each file's real extension, lowercased) so the site's scrollable
card galleries can use them.

It also (re)writes js/gallery-manifest.js, which lists the exact gallery
filenames per project so script.js never has to guess file extensions.

Special cases (kept as close to "all photos in the folder" as practical):
  - Norodom Business Center: the photo archive holds ~38,000 photos (6.5 GB),
    far too many for a website. An even sample from the most recent month
    (2026/09) is used instead.
  - Fengfu: has no "Completion Photos"/"Photos" folder (SITE PHOTO folders
    are empty), so the project's 16 3D renders are used.
"""
import json
import os
import re
import shutil
import sys

ARCHIVE = r"D:\SingBuild's Document"
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_ROOT = os.path.join(REPO_ROOT, "images", "projects")
MANIFEST = os.path.join(REPO_ROOT, "js", "gallery-manifest.js")

NBC_SAMPLE = 16

# slug -> (source folders, sample count or None for all)
PROJECTS = {
    "norodom-business-center": ([r"1. Norodom Business Center\NBC Pan Pacific Hotel - Project Photo Archive - 25 Aug 2025 to 12 September 2026\2026\09 - September"], NBC_SAMPLE),
    "uvp2-retiling": ([r"2. UVP2 - Retilling Work\Completion Photos"], None),
    "uvp2-common-areas": ([r"3. UVP2 - Common Areas\Completion Photos"], None),
    "uvp2-swimming-pool": ([r"4. UVP2 - Swimming Pool\Completion Report\Photos"], None),
    "singapore-airlines": ([r"6. Singapore Airlines Office\Completion Photos"], None),
    "fengfu": ([r"8. Fengfu\Drawing List\Shop Drawing\Shop Drawing\DWG\As of 4.28.25\RENDER\08.11.24",
                r"8. Fengfu\Drawing List\Shop Drawing\Shop Drawing\DWG\As of 4.28.25\RENDER\18mar25"], None),
    "kfk-kmall2": ([r"10. KFK - KMALL 2\Completion Photos"], None),
    "uvp2-penthouse-p5": ([r"11. UVP2 - Penthouse P5\Completion Photos"], None),
}

IMG_RE = re.compile(r"\.(jpe?g|png)$", re.IGNORECASE)


def norm_ext(name):
    ext = os.path.splitext(name)[1].lower()
    return ".jpg" if ext == ".jpeg" else ext


def natural_key(name):
    """Sort so embedded numbers compare numerically (photo_2 before photo_10)."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", name)]


def collect_images(folder):
    files = []
    for name in sorted(os.listdir(folder), key=natural_key):
        if IMG_RE.search(name):
            files.append(os.path.join(folder, name))
    return files


def write_manifest():
    """Regenerate js/gallery-manifest.js from the folders on disk."""
    data = {}
    for slug in sorted(os.listdir(OUT_ROOT)):
        folder = os.path.join(OUT_ROOT, slug)
        if not os.path.isdir(folder):
            continue
        files = sorted(f for f in os.listdir(folder) if IMG_RE.search(f))
        if files:
            data[slug] = files
    with open(MANIFEST, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("/* Generated by tools/build_galleries.py - do not edit by hand.\n")
        fh.write("   Exact gallery filenames per project (extensions vary: jpg/png). */\n")
        fh.write("window.GALLERY_FILES = ")
        fh.write(json.dumps(data, indent=2))
        fh.write(";\n")
    print(f"manifest: {len(data)} galleries -> {MANIFEST}")


def main():
    only = set(sys.argv[1:])
    total_files = 0
    total_bytes = 0
    for slug, (rel_folders, sample) in PROJECTS.items():
        if only and slug not in only:
            continue
        out_dir = os.path.join(OUT_ROOT, slug)
        os.makedirs(out_dir, exist_ok=True)

        sources = []
        for rel in rel_folders:
            folder = os.path.join(ARCHIVE, rel)
            if not os.path.isdir(folder):
                print(f"  !! missing source folder: {folder}")
                continue
            sources.extend(collect_images(folder))

        if not sources:
            print(f"  !! no images found for {slug}")
            continue

        if sample and len(sources) > sample:
            step = len(sources) / sample
            sources = [sources[min(len(sources) - 1, int(i * step))] for i in range(sample)]

        for old in os.listdir(out_dir):
            if IMG_RE.search(old):
                os.remove(os.path.join(out_dir, old))

        for idx, src in enumerate(sources, 1):
            dst = os.path.join(out_dir, f"{idx:02d}{norm_ext(src)}")
            shutil.copyfile(src, dst)  # byte-for-byte copy, original quality
            total_files += 1
            total_bytes += os.path.getsize(dst)

        print(f"{slug}: {len(sources)} photos -> {out_dir}")

    write_manifest()
    print(f"\nDone. {total_files} photos, {total_bytes / (1024 * 1024):.1f} MB total.")


if __name__ == "__main__":
    sys.exit(main())
